# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [169]:
DATA_FOLDER = r'C:\Users\User\git\ADA2017-Tutorials\02-IntrotoPandas\Data' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average* per month of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [56]:
import pandas as pd
import numpy as np
import glob

In [57]:
guinea_folder = r'C:\Users\User\git\ADA2017-Tutorials\02 - Intro to Pandas\Data\ebola\guinea_data'
liberia_folder = r'C:\Users\User\git\ADA2017-Tutorials\02 - Intro to Pandas\Data\ebola\liberia_data'
sl_folder = r'C:\Users\User\git\ADA2017-Tutorials\02 - Intro to Pandas\Data\ebola\sl_data'

In [58]:
all_files_guinea = glob.glob(guinea_folder + "/*.csv")
all_files_liberia = glob.glob(liberia_folder + "/*.csv")
all_files_sl= glob.glob(sl_folder+"\*.csv")

In [59]:
frame_g = pd.DataFrame()
list_g= []
for file_ in all_files_guinea:
    data = pd.read_csv(file_,parse_dates=['Date'], header=0)
    list_g.append(data)
frame_g = pd.concat(list_g)

In [60]:
filtered_data = frame_g.loc[frame_g['Description'].apply(func=lambda x: ('new cases' in x.lower() or 'new deaths' in x.lower()) and 'total' not in x.lower()),:]

In [61]:
guinea_data = filtered_data[['Date','Description','Totals']]

In [62]:
guinea_data = guinea_data.dropna()#dropna is used here to eliminate the NaN values

In [63]:
guinea_data['Totals'] = guinea_data['Totals'].apply(pd.to_numeric, errors='coerce')

In [64]:
guinea_data['Totals'].groupby([guinea_data.Date.dt.month]).agg(['sum','count','mean'])

      sum  count      mean
Date
8     148     30  4.933333
9     378     96  3.937500
10     51      6  8.500000

In [65]:
frame_l = pd.DataFrame()
list_l= []
for file_ in all_files_liberia:
    data = pd.read_csv(file_,parse_dates=['Date'], header=0)
    list_l.append(data)
frame_l = pd.concat(list_l)

In [66]:
frame_l['Total'] = frame_l.sum(axis=1)

In [67]:
filtered_l = frame_l.loc[frame_l['Variable'].apply(func=lambda x: ('cases' in x.lower() or 'deaths' in x.lower()) and ('total') not in x.lower() and ('probable') not in x.lower() and ('cumulative') not in x.lower()),:]

In [68]:
liberia_data = filtered_l[['Date','Variable','Total']]

In [69]:
liberia_data['Total'].groupby([liberia_data.Date.dt.month]).agg(['sum','count','mean'])

         sum  count       mean
Date
6       50.0     21   2.380952
7      120.0     33   3.636364
8      454.0     27  16.814815
9     1828.0     72  25.388889
10    1443.0     75  19.240000
11     417.0     45   9.266667
12       2.0     27   0.074074

In [202]:
frame_s = pd.DataFrame()
list_s= []
for file_ in all_files_sl:
    data = pd.read_csv(file_,parse_dates=['date'], header=0)
    list_s.append(data)
frame_s = pd.concat(list_s)

In [203]:
frame_s

,34 Military Hospital,Bo,Bo EMC,Bombali,Bonthe,Hastings-F/Town,Kailahun,Kambia,Kenema,Kenema (IFRC),...,Port Loko,Pujehun,Tonkolili,Unnamed: 18,Western area,Western area combined,Western area rural,Western area urban,date,variable
0,NaN,654142,NaN,494139,168729,NaN,465048,341690,653013,NaN,...,557978,335574,434937,NaN,NaN,NaN,263619,1040888,2014-08-12,population
1,NaN,0,NaN,0,0,NaN,0,0,3,NaN,...,1,0,0,NaN,NaN,NaN,0,0,2014-08-12,new_noncase
2,NaN,1,NaN,0,0,NaN,0,0,9,NaN,...,0,0,0,NaN,NaN,NaN,0,0,2014-08-12,new_suspected
3,NaN,1,NaN,0,0,NaN,0,0,0,NaN,...,0,0,0,NaN,NaN,NaN,0,0,2014-08-12,new_probable
4,NaN,0,NaN,0,0,NaN,0,0,9,NaN,...,2,0,0,NaN,NaN,NaN,0,0,2014-08-12,new_confirmed
5,NaN,54,NaN,10,0,NaN,201,1,269,NaN,...,7,2,10,NaN,NaN,NaN,5,56,2014-08-12,cum_noncase
6,NaN,2,NaN,1,0,NaN,0,0,10,NaN,...,0,0,0,NaN,NaN,NaN,0,0,2014-08-12,cum_suspected
7,NaN,1,NaN,1,0,NaN,32,0,0,NaN,...,1,0,0,NaN,NaN,NaN,0,1,2014-08-12,cum_probable
8,NaN,22,NaN,7,1,NaN,378,1,259,NaN,...,24,3,2,NaN,NaN,NaN,1,13,2014-08-12,cum_confirmed
9,NaN,0,NaN,0,0,NaN,2,0,1,NaN,...,1,0,0,NaN,NaN,NaN,0,1,2014-08-12,death_suspected
10,NaN,0,NaN,0,0,NaN,32,0,0,NaN,...,1,0,0,NaN,NaN,NaN,0,1,2014-08-12,death_probable
11,NaN,2,NaN,1,0,NaN,151,0,104,NaN,...,1,0,0,NaN,NaN,NaN,0,2,2014-08-12,death_confirmed
12,NaN,9.1,NaN,14.3,0,NaN,39.9,0,40.2,NaN,...,4.2,0,0,NaN,NaN,NaN,0,15.4,2014-08-12,cfr
13,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_new_admission
14,NaN,NaN,NaN,NaN,NaN,NaN,53,NaN,41,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_currently_admitted
15,NaN,NaN,NaN,NaN,NaN,NaN,341,NaN,303,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_cum_admission
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_new_deaths
17,NaN,NaN,NaN,NaN,NaN,NaN,104,NaN,154,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_cum_deaths
18,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_new_discharges
19,NaN,NaN,NaN,NaN,NaN,NaN,134,NaN,59,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_cum_discharges
20,NaN,227,NaN,161,26,NaN,NaN,0,"1,356",NaN,...,471,57,16,NaN,NaN,NaN,23,390,2014-08-12,cum_contacts
21,NaN,67,NaN,16,26,NaN,NaN,0,701,NaN,...,7,10,0,NaN,NaN,NaN,0,82,2014-08-12,cum_completed_contacts
22,NaN,160,NaN,161,0,NaN,321,0,497,NaN,...,466,47,11,NaN,NaN,NaN,23,310,2014-08-12,contacts_followed
23,NaN,6,NaN,5,0,NaN,321,0,73,NaN,...,308,0,5,NaN,NaN,NaN,0,25,2014-08-12,new_contacts
24,NaN,157,NaN,141,0,NaN,305,0,427,NaN,...,443,47,11,NaN,NaN,NaN,23,103,2014-08-12,contacts_healthy
25,NaN,0,NaN,0,0,NaN,11,0,3,NaN,...,0,0,0,NaN,NaN,NaN,0,0,2014-08-12,contacts_ill
26,NaN,3,NaN,20,0,NaN,16,0,64,NaN,...,28,0,0,NaN,NaN,NaN,0,0,2014-08-12,contacts_not_seen
27,NaN,0,NaN,16,0,NaN,12,0,38,NaN,...,0,1,0,NaN,NaN,NaN,0,6,2014-08-12,new_completed_contacts
28,NaN,98%,NaN,97%,NaN,NaN,98%,NaN,61%,NaN,...,95%,100%,100%,NaN,NaN,NaN,100%,101%,2014-08-12,percent_seen
0,NaN,"654,142",NaN,"494,139","168,729",NaN,"465,048","341,690","653,013",NaN,...,"557,978","335,574","434,937",NaN,NaN,NaN,"263,619","1,040,888",2014-08-13,population
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,NaN,1,NaN,6,0,NaN,32,0,0,NaN,...,1,0,4,NaN,NaN,NaN,0,1,2014-12-13,cum_probable
8,NaN,297,NaN,907,4,NaN,565,96,495,NaN,...,998,31,396,NaN,NaN,NaN,937,1526,2014-12-13,cum_confirmed
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,death_suspected
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,death_probable
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,death_confirmed
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,cfr
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_new_admission
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_currently_admitted
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_cum_admission
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_new_deaths
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_cum_deaths
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_new_discharges
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_cum_discharges
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,cum_contacts
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,cum_completed_contacts
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,contacts_followed
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_contacts
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,contacts_healthy
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,contacts_ill
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,contacts_not_seen
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_completed_contacts
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,percent_seen
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,total_lab_samples
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,repeat_samples
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_samples
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_positive
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_negative
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,pending
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,positive_corpse
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,negative_corpse

In [252]:
filtered_s = frame_s.loc[frame_s['variable'].apply(func=lambda x: ('new' in x.lower() or 'deaths' in x.lower()) and ('cum') not in x.lower() and ('probable') not in x.lower() and ('suspected') not in x.lower()and ('contacts') not in x.lower()and ('noncase') not in x.lower() and ('negative') not in x.lower() and ('discharges') not in x.lower() and ('samples') not in x.lower() and ('admission') not in x.lower()),:]

In [253]:
filtered_s

,34 Military Hospital,Bo,Bo EMC,Bombali,Bonthe,Hastings-F/Town,Kailahun,Kambia,Kenema,Kenema (IFRC),...,Port Loko,Pujehun,Tonkolili,Unnamed: 18,Western area,Western area combined,Western area rural,Western area urban,date,variable
4,NaN,0,NaN,0,0,NaN,0,0,9,NaN,...,2,0,0,NaN,NaN,NaN,0,0,2014-08-12,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_new_deaths
4,NaN,1,NaN,0,0,NaN,11,0,1,NaN,...,0,0,0,NaN,NaN,NaN,0,2,2014-08-13,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-13,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,0,0,8,NaN,...,2,0,0,NaN,NaN,NaN,2,0,2014-08-14,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-14,etc_new_deaths
4,NaN,1,NaN,0,0,NaN,0,0,3,NaN,...,2,0,0,NaN,NaN,NaN,0,4,2014-08-15,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-15,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,12,0,4,NaN,...,0,0,0,NaN,NaN,NaN,1,1,2014-08-16,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-16,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,0,0,2,NaN,...,0,0,0,NaN,NaN,NaN,0,0,2014-08-17,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-17,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,5,0,0,NaN,...,0,0,0,NaN,NaN,NaN,0,0,2014-08-18,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-18,etc_new_deaths
4,NaN,2,NaN,0,0,NaN,3,0,2,NaN,...,0,0,0,NaN,NaN,NaN,0,2,2014-08-19,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-19,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,1,0,2,NaN,...,1,0,0,NaN,NaN,NaN,0,0,2014-08-20,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-20,etc_new_deaths
4,NaN,1,NaN,0,0,NaN,1,0,0,NaN,...,0,0,6,NaN,NaN,NaN,1,0,2014-08-21,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-21,etc_new_deaths
4,NaN,6,NaN,6,0,NaN,6,0,12,NaN,...,13,1,2,NaN,NaN,NaN,5,4,2014-08-22,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-22,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,11,0,5,NaN,...,7,0,0,NaN,NaN,NaN,0,0,2014-08-23,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-23,etc_new_deaths
4,NaN,2,NaN,0,0,NaN,12,0,12,NaN,...,0,0,1,NaN,NaN,NaN,1,3,2014-08-24,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-24,etc_new_deaths
4,NaN,0,NaN,3,0,NaN,0,0,6,NaN,...,3,2,2,NaN,NaN,NaN,3,1,2014-08-25,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-25,etc_new_deaths
4,NaN,0,NaN,0,0,NaN,0,0,2,NaN,...,0,0,0,NaN,NaN,NaN,0,4,2014-08-26,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-26,etc_new_deaths
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,NaN,1,NaN,4,0,NaN,0,0,0,NaN,...,3,0,5,NaN,NaN,NaN,7,26,2014-11-22,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-22,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-22,new_positive
4,NaN,0,NaN,0,0,NaN,0,2,0,NaN,...,13,0,3,NaN,NaN,NaN,8,11,2014-11-23,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-23,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-23,new_positive
4,NaN,8,NaN,10,0,NaN,0,6,0,NaN,...,13,0,4,NaN,NaN,NaN,10,31,2014-11-24,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-24,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-24,new_positive
4,NaN,4,NaN,11,0,NaN,0,0,0,NaN,...,14,1,7,NaN,NaN,NaN,3,42,2014-11-28,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-28,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-28,new_positive
4,NaN,2,NaN,77,0,NaN,1,1,0,NaN,...,0,0,1,NaN,NaN,NaN,11,26,2014-11-29,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-29,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-29,new_positive
4,NaN,3,NaN,10,0,NaN,0,1,0,NaN,...,26,0,0,NaN,NaN,NaN,6,24,2014-12-01,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-01,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-01,new_positive
4,NaN,1,NaN,0,0,NaN,0,1,0,NaN,...,20,0,1,NaN,NaN,NaN,5,8,2014-12-04,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-04,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-04,new_positive
4,NaN,1,NaN,11,0,NaN,0,4,0,NaN,...,10,0,1,NaN,NaN,NaN,5,15,2014-12-05,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-05,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-05,new_positive
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-06,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-06,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-06,new_positive
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_confirmed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_new_deaths
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_positive

In [254]:
medium = filtered_s[filtered_s.columns.difference(['variable'])]

In [255]:
medium.dtypes

34 Military Hospital             float64
Bo                                object
Bo EMC                           float64
Bombali                           object
Bonthe                            object
Hastings-F/Town                  float64
Kailahun                          object
Kambia                            object
Kenema                            object
Kenema (IFRC)                    float64
Kenema (KGH)                      object
Koinadugu                         object
Kono                              object
Moyamba                           object
National                          object
Police training School           float64
Police traning School            float64
Port Loko                         object
Pujehun                           object
Tonkolili                         object
Unnamed: 18                      float64
Western area                     float64
Western area combined            float64
Western area rural                object
Western area urban                object
date                      datetime64[ns]
dtype: object

In [256]:
medium = medium.select_dtypes(include = ['object'])

In [257]:
medium.dtypes

Bo                    object
Bombali               object
Bonthe                object
Kailahun              object
Kambia                object
Kenema                object
Kenema (KGH)          object
Koinadugu             object
Kono                  object
Moyamba               object
National              object
Port Loko             object
Pujehun               object
Tonkolili             object
Western area rural    object
Western area urban    object
dtype: object

In [258]:
medium = medium.apply(pd.to_numeric,errors='coerce')

In [259]:
medium.dtypes

Bo                    float64
Bombali               float64
Bonthe                float64
Kailahun              float64
Kambia                float64
Kenema                float64
Kenema (KGH)          float64
Koinadugu             float64
Kono                  float64
Moyamba               float64
National              float64
Port Loko             float64
Pujehun               float64
Tonkolili             float64
Western area rural    float64
Western area urban    float64
dtype: object

In [260]:
medium['Total'] = medium.sum(axis=1)

In [261]:
medium

,Bo,Bombali,Bonthe,Kailahun,Kambia,Kenema,Kenema (KGH),Koinadugu,Kono,Moyamba,National,Port Loko,Pujehun,Tonkolili,Western area rural,Western area urban,Total
4,0.0,0.0,0.0,0.0,0.0,9.0,NaN,0.0,0.0,0.0,11.0,2.0,0.0,0.0,0.0,0.0,22.0
16,NaN,NaN,NaN,5.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
4,1.0,0.0,0.0,11.0,0.0,1.0,NaN,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,2.0,30.0
16,NaN,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
4,0.0,0.0,0.0,0.0,0.0,8.0,NaN,0.0,0.0,1.0,13.0,2.0,0.0,0.0,2.0,0.0,26.0
16,NaN,NaN,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
4,1.0,0.0,0.0,0.0,0.0,3.0,NaN,0.0,0.0,0.0,10.0,2.0,0.0,0.0,0.0,4.0,20.0
16,NaN,NaN,NaN,5.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
4,0.0,0.0,0.0,12.0,0.0,4.0,NaN,0.0,0.0,0.0,18.0,0.0,0.0,0.0,1.0,1.0,36.0
16,NaN,NaN,NaN,5.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,0.0,0.0,0.0,0.0,0.0,2.0,NaN,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0
16,NaN,NaN,NaN,3.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
4,0.0,0.0,0.0,5.0,0.0,0.0,NaN,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,10.0
16,NaN,NaN,NaN,6.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
4,2.0,0.0,0.0,3.0,0.0,2.0,NaN,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,2.0,18.0
16,NaN,NaN,NaN,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
4,0.0,0.0,0.0,1.0,0.0,2.0,NaN,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,8.0
16,NaN,NaN,NaN,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,1.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,9.0,0.0,0.0,6.0,1.0,0.0,18.0
16,NaN,NaN,NaN,3.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
4,6.0,6.0,0.0,6.0,0.0,12.0,NaN,0.0,0.0,1.0,56.0,13.0,1.0,2.0,5.0,4.0,112.0
16,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,0.0,0.0,0.0,11.0,0.0,5.0,NaN,0.0,0.0,0.0,23.0,7.0,0.0,0.0,0.0,0.0,46.0
16,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
4,2.0,0.0,0.0,12.0,0.0,12.0,NaN,0.0,0.0,0.0,31.0,0.0,0.0,1.0,1.0,3.0,62.0
16,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,0.0,3.0,0.0,0.0,0.0,6.0,NaN,0.0,0.0,0.0,20.0,3.0,2.0,2.0,3.0,1.0,40.0
16,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,0.0,0.0,0.0,0.0,0.0,2.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,4.0,6.0
16,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1.0,4.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,47.0,3.0,0.0,5.0,7.0,26.0,94.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,47.0
4,0.0,0.0,0.0,0.0,2.0,0.0,NaN,0.0,1.0,1.0,39.0,13.0,0.0,3.0,8.0,11.0,78.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,NaN,NaN,NaN,NaN,NaN,39.0
4,8.0,10.0,0.0,0.0,6.0,0.0,NaN,0.0,0.0,1.0,83.0,13.0,0.0,4.0,10.0,31.0,166.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.0,NaN,NaN,NaN,NaN,NaN,83.0
4,4.0,11.0,0.0,0.0,0.0,0.0,NaN,2.0,0.0,0.0,84.0,14.0,1.0,7.0,3.0,42.0,168.0
16,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,2.0,77.0,0.0,1.0,1.0,0.0,NaN,0.0,15.0,0.0,64.0,0.0,0.0,1.0,11.0,26.0,198.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,3.0,10.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0,2.0,72.0,26.0,0.0,0.0,6.0,24.0,144.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0,1.0,37.0,20.0,0.0,1.0,5.0,8.0,74.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,37.0
4,1.0,11.0,0.0,0.0,4.0,0.0,NaN,0.0,7.0,0.0,54.0,10.0,0.0,1.0,5.0,15.0,108.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,8.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,NaN,NaN,NaN,54.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [262]:
filtered_s['Total'] = medium['Total']

C:\Users\User\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [263]:
filtered_s

,34 Military Hospital,Bo,Bo EMC,Bombali,Bonthe,Hastings-F/Town,Kailahun,Kambia,Kenema,Kenema (IFRC),...,Pujehun,Tonkolili,Unnamed: 18,Western area,Western area combined,Western area rural,Western area urban,date,variable,Total
4,NaN,0,NaN,0,0,NaN,0,0,9,NaN,...,0,0,NaN,NaN,NaN,0,0,2014-08-12,new_confirmed,22.0
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-12,etc_new_deaths,8.0
4,NaN,1,NaN,0,0,NaN,11,0,1,NaN,...,0,0,NaN,NaN,NaN,0,2,2014-08-13,new_confirmed,30.0
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-13,etc_new_deaths,6.0
4,NaN,0,NaN,0,0,NaN,0,0,8,NaN,...,0,0,NaN,NaN,NaN,2,0,2014-08-14,new_confirmed,26.0
16,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-14,etc_new_deaths,7.0
4,NaN,1,NaN,0,0,NaN,0,0,3,NaN,...,0,0,NaN,NaN,NaN,0,4,2014-08-15,new_confirmed,20.0
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-15,etc_new_deaths,7.0
4,NaN,0,NaN,0,0,NaN,12,0,4,NaN,...,0,0,NaN,NaN,NaN,1,1,2014-08-16,new_confirmed,36.0
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-16,etc_new_deaths,10.0
4,NaN,0,NaN,0,0,NaN,0,0,2,NaN,...,0,0,NaN,NaN,NaN,0,0,2014-08-17,new_confirmed,4.0
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-17,etc_new_deaths,8.0
4,NaN,0,NaN,0,0,NaN,5,0,0,NaN,...,0,0,NaN,NaN,NaN,0,0,2014-08-18,new_confirmed,10.0
16,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-18,etc_new_deaths,7.0
4,NaN,2,NaN,0,0,NaN,3,0,2,NaN,...,0,0,NaN,NaN,NaN,0,2,2014-08-19,new_confirmed,18.0
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-19,etc_new_deaths,6.0
4,NaN,0,NaN,0,0,NaN,1,0,2,NaN,...,0,0,NaN,NaN,NaN,0,0,2014-08-20,new_confirmed,8.0
16,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-20,etc_new_deaths,2.0
4,NaN,1,NaN,0,0,NaN,1,0,0,NaN,...,0,6,NaN,NaN,NaN,1,0,2014-08-21,new_confirmed,18.0
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-21,etc_new_deaths,7.0
4,NaN,6,NaN,6,0,NaN,6,0,12,NaN,...,1,2,NaN,NaN,NaN,5,4,2014-08-22,new_confirmed,112.0
16,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-22,etc_new_deaths,4.0
4,NaN,0,NaN,0,0,NaN,11,0,5,NaN,...,0,0,NaN,NaN,NaN,0,0,2014-08-23,new_confirmed,46.0
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-23,etc_new_deaths,3.0
4,NaN,2,NaN,0,0,NaN,12,0,12,NaN,...,0,1,NaN,NaN,NaN,1,3,2014-08-24,new_confirmed,62.0
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-24,etc_new_deaths,5.0
4,NaN,0,NaN,3,0,NaN,0,0,6,NaN,...,2,2,NaN,NaN,NaN,3,1,2014-08-25,new_confirmed,40.0
16,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-25,etc_new_deaths,5.0
4,NaN,0,NaN,0,0,NaN,0,0,2,NaN,...,0,0,NaN,NaN,NaN,0,4,2014-08-26,new_confirmed,6.0
16,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-08-26,etc_new_deaths,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,NaN,1,NaN,4,0,NaN,0,0,0,NaN,...,0,5,NaN,NaN,NaN,7,26,2014-11-22,new_confirmed,94.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-22,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-22,new_positive,47.0
4,NaN,0,NaN,0,0,NaN,0,2,0,NaN,...,0,3,NaN,NaN,NaN,8,11,2014-11-23,new_confirmed,78.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-23,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-23,new_positive,39.0
4,NaN,8,NaN,10,0,NaN,0,6,0,NaN,...,0,4,NaN,NaN,NaN,10,31,2014-11-24,new_confirmed,166.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-24,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-24,new_positive,83.0
4,NaN,4,NaN,11,0,NaN,0,0,0,NaN,...,1,7,NaN,NaN,NaN,3,42,2014-11-28,new_confirmed,168.0
16,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-28,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-28,new_positive,0.0
4,NaN,2,NaN,77,0,NaN,1,1,0,NaN,...,0,1,NaN,NaN,NaN,11,26,2014-11-29,new_confirmed,198.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-29,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-11-29,new_positive,0.0
4,NaN,3,NaN,10,0,NaN,0,1,0,NaN,...,0,0,NaN,NaN,NaN,6,24,2014-12-01,new_confirmed,144.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-01,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-01,new_positive,0.0
4,NaN,1,NaN,0,0,NaN,0,1,0,NaN,...,0,1,NaN,NaN,NaN,5,8,2014-12-04,new_confirmed,74.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-04,etc_new_deaths,3.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-04,new_positive,37.0
4,NaN,1,NaN,11,0,NaN,0,4,0,NaN,...,0,1,NaN,NaN,NaN,5,15,2014-12-05,new_confirmed,108.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-05,etc_new_deaths,8.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-05,new_positive,54.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-06,new_confirmed,0.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-06,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-06,new_positive,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_confirmed,0.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,etc_new_deaths,0.0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-13,new_positive,0.0

In [265]:
filtered_s['Total'].groupby([filtered_s.date.dt.month]).agg(['sum','count','mean'])

         sum  count       mean
date
8      874.0     40  21.850000
9     2164.0     58  37.310345
10    3461.0     64  54.078125
11    3394.0     63  53.873016
12     428.0     15  28.533333

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [3]:
import pandas as pd
import numpy as np
import glob

In [4]:
bio_folder = r'C:\Users\User\git\ADA2017-Tutorials\02 - Intro to Pandas\Data\microbiome'

In [5]:
all_files = glob.glob(bio_folder + "/MID?.xls")

In [6]:
metadata=pd.read_excel(bio_folder+"/metadata.xls", header=0)

In [7]:
frame = pd.DataFrame()
list_ = []
i=0
for file_ in all_files:
    i = i+1
    data = pd.read_excel(file_, header=None)
    data['Group']= metadata.loc[metadata['BARCODE'] == ('MID'+str(i)), 'GROUP'].iloc[0]
    data['Sample']=metadata.loc[metadata['BARCODE'] == ('MID'+str(i)), 'SAMPLE'].iloc[0]
    list_.append(data)
metadata=pd.read_excel(bio_folder+"/metadata.xls", header=None)
frame = pd.concat(list_)

In [8]:
frame

,0,1,Group,Sample
0,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",7,EXTRACTION CONTROL,NaN
1,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",2,EXTRACTION CONTROL,NaN
2,"Archaea ""Crenarchaeota"" Thermoprotei Sulfoloba...",3,EXTRACTION CONTROL,NaN
3,"Archaea ""Crenarchaeota"" Thermoprotei Thermopro...",3,EXTRACTION CONTROL,NaN
4,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",7,EXTRACTION CONTROL,NaN
5,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,EXTRACTION CONTROL,NaN
6,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,EXTRACTION CONTROL,NaN
7,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,EXTRACTION CONTROL,NaN
8,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,EXTRACTION CONTROL,NaN
9,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,EXTRACTION CONTROL,NaN
10,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,EXTRACTION CONTROL,NaN
11,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,EXTRACTION CONTROL,NaN
12,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",2,EXTRACTION CONTROL,NaN
13,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,EXTRACTION CONTROL,NaN
14,"Archaea ""Euryarchaeota"" Methanococci Methanoco...",1,EXTRACTION CONTROL,NaN
15,"Archaea ""Euryarchaeota"" Methanopyri Methanopyr...",12,EXTRACTION CONTROL,NaN
16,"Archaea ""Euryarchaeota"" Thermoplasmata Thermop...",2,EXTRACTION CONTROL,NaN
17,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,NaN
18,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,NaN
19,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,NaN
20,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,NaN
21,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,NaN
22,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",53,EXTRACTION CONTROL,NaN
23,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,NaN
24,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,NaN
25,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",3,EXTRACTION CONTROL,NaN
26,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,NaN
27,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",99,EXTRACTION CONTROL,NaN
28,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",17,EXTRACTION CONTROL,NaN
29,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,NaN
...,...,...,...,...
251,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",10,Control 2,stool
252,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
253,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
254,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
255,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,Control 2,stool
256,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,Control 2,stool
257,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",805,Control 2,stool
258,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",862,Control 2,stool
259,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,Control 2,stool
260,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3534,Control 2,stool
261,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,Control 2,stool
262,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
263,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",25,Control 2,stool
264,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
265,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,Control 2,stool
266,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
267,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
268,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,Control 2,stool
269,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
270,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
271,"Bacteria ""Synergistetes"" Synergistia Synergist...",3,Control 2,stool
272,"Bacteria ""Tenericutes"" Mollicutes Anaeroplasma...",1,Control 2,stool
273,"Bacteria ""Tenericutes"" Mollicutes Haloplasmata...",11,Control 2,stool
274,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,Control 2,stool
275,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,Control 2,stool
276,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",43,Control 2,stool
277,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",16,Control 2,stool
278,"Bacteria ""Verrucomicrobia"" Opitutae Opitutales...",1,Control 2,stool
279,Bacteria Cyanobacteria Cyanobacteria Chloropl...,1,Control 2,stool
280,Bacteria Cyanobacteria Cyanobacteria Chloropl...,10,Control 2,stool

In [19]:
frame = frame.reset_index() # I reset the index to inquire new unique indexes

In [20]:
frame.fillna('unknown') #replace all NaN with unknown as required

,index,0,1,Group,Sample
0,0,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",7,EXTRACTION CONTROL,unknown
1,1,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",2,EXTRACTION CONTROL,unknown
2,2,"Archaea ""Crenarchaeota"" Thermoprotei Sulfoloba...",3,EXTRACTION CONTROL,unknown
3,3,"Archaea ""Crenarchaeota"" Thermoprotei Thermopro...",3,EXTRACTION CONTROL,unknown
4,4,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",7,EXTRACTION CONTROL,unknown
5,5,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,EXTRACTION CONTROL,unknown
6,6,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,EXTRACTION CONTROL,unknown
7,7,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,EXTRACTION CONTROL,unknown
8,8,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,EXTRACTION CONTROL,unknown
9,9,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,EXTRACTION CONTROL,unknown
10,10,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,EXTRACTION CONTROL,unknown
11,11,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,EXTRACTION CONTROL,unknown
12,12,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",2,EXTRACTION CONTROL,unknown
13,13,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,EXTRACTION CONTROL,unknown
14,14,"Archaea ""Euryarchaeota"" Methanococci Methanoco...",1,EXTRACTION CONTROL,unknown
15,15,"Archaea ""Euryarchaeota"" Methanopyri Methanopyr...",12,EXTRACTION CONTROL,unknown
16,16,"Archaea ""Euryarchaeota"" Thermoplasmata Thermop...",2,EXTRACTION CONTROL,unknown
17,17,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
18,18,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
19,19,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
20,20,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
21,21,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
22,22,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",53,EXTRACTION CONTROL,unknown
23,23,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
24,24,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
25,25,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",3,EXTRACTION CONTROL,unknown
26,26,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
27,27,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",99,EXTRACTION CONTROL,unknown
28,28,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",17,EXTRACTION CONTROL,unknown
29,29,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
...,...,...,...,...,...
2366,251,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",10,Control 2,stool
2367,252,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2368,253,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2369,254,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2370,255,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,Control 2,stool
2371,256,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,Control 2,stool
2372,257,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",805,Control 2,stool
2373,258,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",862,Control 2,stool
2374,259,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,Control 2,stool
2375,260,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3534,Control 2,stool
2376,261,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,Control 2,stool
2377,262,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2378,263,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",25,Control 2,stool
2379,264,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
2380,265,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,Control 2,stool
2381,266,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
2382,267,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2383,268,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,Control 2,stool
2384,269,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
2385,270,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2386,271,"Bacteria ""Synergistetes"" Synergistia Synergist...",3,Control 2,stool
2387,272,"Bacteria ""Tenericutes"" Mollicutes Anaeroplasma...",1,Control 2,stool
2388,273,"Bacteria ""Tenericutes"" Mollicutes Haloplasmata...",11,Control 2,stool
2389,274,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,Control 2,stool
2390,275,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,Control 2,stool
2391,276,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",43,Control 2,stool
2392,277,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",16,Control 2,stool
2393,278,"Bacteria ""Verrucomicrobia"" Opitutae Opitutales...",1,Control 2,stool
2394,279,Bacteria Cyanobacteria Cyanobacteria Chloropl...,1,Control 2,stool
2395,280,Bacteria Cyanobacteria Cyanobacteria Chloropl...,10,Control 2,stool

In [162]:
frame[Group]

NameError: name 'Group' is not defined

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [163]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

NameError: name 'DATA_FOLDER' is not defined

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [164]:
# Write your answer here

In [1]:
plt.__version__

NameError: name 'plt' is not defined